/**
 * GENERATED by scripts/runner_effect_rows.py --media from the real node
 * classes (define_schema / INPUT_TYPES). Do not edit: run the script again.
 *
 * The video and sound effects the runner ports (step 3, R6): 21 video and
 * 12 sound effects, and Save audio (Opus) (R5's `media-sound`), each with its
 * family, frame-batch (IMAGE) and sound (AUDIO) inputs, widgets as ComfyUI's
 * validate_inputs reads them, outputs, and whether it is an output node. A
 * `fileList` widget is a COMBO of a folder's files (written with no options).
 */

export type MediaEffectSchemaFamily = 'video-time' | 'video-join' | 'video-look' | 'video-stabilize' | 'video-flow' | 'video-draw' | 'video-text' | 'sound-effects' | 'sound-denoise' | 'media-sound'

export interface MediaEffectSchemaInput { name: string; required: boolean }

export interface MediaEffectSchemaWidget {
  type: 'FLOAT' | 'INT' | 'BOOLEAN' | 'STRING' | 'COMBO'
  required: boolean
  min?: number
  max?: number
  options?: readonly string[]
  fileList?: true
}

export interface MediaEffectSchema {
  family: MediaEffectSchemaFamily
  frames: readonly MediaEffectSchemaInput[]
  sounds: readonly MediaEffectSchemaInput[]
  widgets: Readonly<Record<string, MediaEffectSchemaWidget>>
  outputs: readonly ('image' | 'mask' | 'audio')[]
  outputNode: boolean
}

export const MEDIA_EFFECT_SCHEMAS: Readonly<Record<string, MediaEffectSchema>> = {
  AnimatedNoise: {
    family: "video-draw",
    frames: [],
    sounds: [],
    widgets: {
      "width": {"type": "INT", "required": true, "min": 64, "max": 2048},
      "height": {"type": "INT", "required": true, "min": 64, "max": 2048},
      "frame_count": {"type": "INT", "required": true, "min": 2, "max": 600},
      "noise_scale": {"type": "FLOAT", "required": true, "min": 4.0, "max": 400.0},
      "speed": {"type": "FLOAT", "required": true, "min": 0.0, "max": 20.0},
      "motion": {"type": "COMBO", "required": true, "options": ["pan_x", "pan_y", "diagonal", "breathe", "swirl"]},
      "dark_color": {"type": "STRING", "required": true},
      "light_color": {"type": "STRING", "required": true},
      "seed": {"type": "INT", "required": true, "min": 0, "max": 2147483647},
    },
    outputs: ["image"],
    outputNode: true,
  },
  AspectConvert: {
    family: "video-look",
    frames: [{"name": "frames", "required": true}],
    sounds: [],
    widgets: {
      "target": {"type": "COMBO", "required": true, "options": ["9:16", "1:1", "4:5", "16:9", "21:9", "4:3", "3:4"]},
      "method": {"type": "COMBO", "required": true, "options": ["crop_center", "pad", "auto_pan"]},
      "pad_color": {"type": "STRING", "required": true},
    },
    outputs: ["image"],
    outputNode: true,
  },
  AudioAdjustVolume: {
    family: "sound-effects",
    frames: [],
    sounds: [{"name": "audio", "required": true}],
    widgets: {
      "volume": {"type": "INT", "required": true, "min": -100, "max": 100},
    },
    outputs: ["audio"],
    outputNode: false,
  },
  AudioConcat: {
    family: "sound-effects",
    frames: [],
    sounds: [{"name": "audio1", "required": true}, {"name": "audio2", "required": true}],
    widgets: {
      "direction": {"type": "COMBO", "required": true, "options": ["after", "before"]},
    },
    outputs: ["audio"],
    outputNode: false,
  },
  AudioDenoise: {
    family: "sound-denoise",
    frames: [],
    sounds: [{"name": "audio", "required": true}],
    widgets: {
      "strength": {"type": "FLOAT", "required": true, "min": 0.0, "max": 1.0},
      "noise_type": {"type": "COMBO", "required": true, "options": ["stationary", "non_stationary"]},
    },
    outputs: ["audio"],
    outputNode: false,
  },
  AudioDuck: {
    family: "sound-effects",
    frames: [],
    sounds: [{"name": "audio", "required": true}, {"name": "sidechain", "required": true}],
    widgets: {
      "threshold_db": {"type": "FLOAT", "required": true, "min": -60.0, "max": 0.0},
      "depth_db": {"type": "FLOAT", "required": true, "min": -60.0, "max": 0.0},
      "attack_ms": {"type": "FLOAT", "required": true, "min": 1.0, "max": 2000.0},
      "release_ms": {"type": "FLOAT", "required": true, "min": 1.0, "max": 5000.0},
    },
    outputs: ["audio"],
    outputNode: false,
  },
  AudioEqualizer3Band: {
    family: "sound-effects",
    frames: [],
    sounds: [{"name": "audio", "required": true}],
    widgets: {
      "low_gain_dB": {"type": "FLOAT", "required": true, "min": -24.0, "max": 24.0},
      "low_freq": {"type": "INT", "required": true, "min": 20, "max": 500},
      "mid_gain_dB": {"type": "FLOAT", "required": true, "min": -24.0, "max": 24.0},
      "mid_freq": {"type": "INT", "required": true, "min": 200, "max": 4000},
      "mid_q": {"type": "FLOAT", "required": true, "min": 0.1, "max": 10.0},
      "high_gain_dB": {"type": "FLOAT", "required": true, "min": -24.0, "max": 24.0},
      "high_freq": {"type": "INT", "required": true, "min": 1000, "max": 15000},
    },
    outputs: ["audio"],
    outputNode: false,
  },
  AudioFade: {
    family: "sound-effects",
    frames: [],
    sounds: [{"name": "audio", "required": true}],
    widgets: {
      "fade_in": {"type": "FLOAT", "required": true, "min": 0.0, "max": 60.0},
      "fade_out": {"type": "FLOAT", "required": true, "min": 0.0, "max": 60.0},
      "curve": {"type": "COMBO", "required": true, "options": ["linear", "equal_power", "exponential"]},
    },
    outputs: ["audio"],
    outputNode: false,
  },
  AudioMerge: {
    family: "sound-effects",
    frames: [],
    sounds: [{"name": "audio1", "required": true}, {"name": "audio2", "required": true}],
    widgets: {
      "merge_method": {"type": "COMBO", "required": true, "options": ["add", "mean", "subtract", "multiply"]},
    },
    outputs: ["audio"],
    outputNode: false,
  },
  AudioNormalize: {
    family: "sound-effects",
    frames: [],
    sounds: [{"name": "audio", "required": true}],
    widgets: {
      "mode": {"type": "COMBO", "required": true, "options": ["peak", "rms"]},
      "target_db": {"type": "FLOAT", "required": true, "min": -60.0, "max": 0.0},
    },
    outputs: ["audio"],
    outputNode: false,
  },
  AudioWaveform: {
    family: "video-draw",
    frames: [],
    sounds: [],
    widgets: {
      "audio_file": {"type": "COMBO", "required": true, "fileList": true},
      "width": {"type": "INT", "required": true, "min": 64, "max": 4096},
      "height": {"type": "INT", "required": true, "min": 64, "max": 4096},
      "fps": {"type": "INT", "required": true, "min": 1, "max": 120},
      "frame_count": {"type": "INT", "required": true, "min": 1, "max": 10000},
      "style": {"type": "COMBO", "required": true, "options": ["bars", "wave", "dots", "radial", "mirrored_bars"]},
      "bar_count": {"type": "INT", "required": true, "min": 4, "max": 512},
      "color": {"type": "STRING", "required": true},
      "bg_color": {"type": "STRING", "required": true},
      "sensitivity": {"type": "FLOAT", "required": true, "min": 0.1, "max": 10.0},
      "smoothing": {"type": "FLOAT", "required": true, "min": 0.0, "max": 0.95},
    },
    outputs: ["image"],
    outputNode: true,
  },
  CaptionTrack: {
    family: "video-text",
    frames: [{"name": "frames", "required": true}],
    sounds: [],
    widgets: {
      "captions": {"type": "STRING", "required": true},
      "font_size": {"type": "INT", "required": true, "min": 8, "max": 256},
      "color": {"type": "STRING", "required": true},
      "outline_color": {"type": "STRING", "required": true},
      "outline_width": {"type": "INT", "required": true, "min": 0, "max": 12},
      "position": {"type": "COMBO", "required": true, "options": ["bottom", "top", "middle"]},
      "y_inset": {"type": "FLOAT", "required": true, "min": 0.0, "max": 0.4},
    },
    outputs: ["image"],
    outputNode: true,
  },
  ChromaKey: {
    family: "video-look",
    frames: [{"name": "frames", "required": true}],
    sounds: [],
    widgets: {
      "key_color": {"type": "STRING", "required": true},
      "tolerance": {"type": "FLOAT", "required": true, "min": 0.0, "max": 1.0},
      "smoothness": {"type": "FLOAT", "required": true, "min": 0.0, "max": 0.5},
      "spill_suppression": {"type": "FLOAT", "required": true, "min": 0.0, "max": 1.0},
      "bg_color": {"type": "STRING", "required": true},
    },
    outputs: ["image", "mask"],
    outputNode: true,
  },
  EmptyAudio: {
    family: "sound-effects",
    frames: [],
    sounds: [],
    widgets: {
      "duration": {"type": "FLOAT", "required": true, "min": 0.0, "max": 18446744073709551615},
      "sample_rate": {"type": "INT", "required": true, "min": 1, "max": 192000},
      "channels": {"type": "INT", "required": true, "min": 1, "max": 2},
    },
    outputs: ["audio"],
    outputNode: false,
  },
  FrameInterpolate: {
    family: "video-flow",
    frames: [{"name": "frames", "required": true}],
    sounds: [],
    widgets: {
      "multiplier": {"type": "INT", "required": true, "min": 2, "max": 8},
    },
    outputs: ["image"],
    outputNode: false,
  },
  FrameTrail: {
    family: "video-time",
    frames: [{"name": "frames", "required": true}],
    sounds: [],
    widgets: {
      "decay": {"type": "FLOAT", "required": true, "min": 0.0, "max": 0.99},
      "blend_mode": {"type": "COMBO", "required": true, "options": ["screen", "add", "max"]},
      "intensity": {"type": "FLOAT", "required": true, "min": 0.0, "max": 2.0},
      "threshold": {"type": "FLOAT", "required": true, "min": 0.0, "max": 1.0},
    },
    outputs: ["image"],
    outputNode: true,
  },
  JoinAudioChannels: {
    family: "sound-effects",
    frames: [],
    sounds: [{"name": "audio_left", "required": true}, {"name": "audio_right", "required": true}],
    widgets: {},
    outputs: ["audio"],
    outputNode: false,
  },
  KenBurns: {
    family: "video-look",
    frames: [{"name": "frames", "required": true}],
    sounds: [],
    widgets: {
      "start_zoom": {"type": "FLOAT", "required": true, "min": 1.0, "max": 4.0},
      "end_zoom": {"type": "FLOAT", "required": true, "min": 1.0, "max": 4.0},
      "start_x": {"type": "FLOAT", "required": true, "min": -0.5, "max": 0.5},
      "start_y": {"type": "FLOAT", "required": true, "min": -0.5, "max": 0.5},
      "end_x": {"type": "FLOAT", "required": true, "min": -0.5, "max": 0.5},
      "end_y": {"type": "FLOAT", "required": true, "min": -0.5, "max": 0.5},
      "easing": {"type": "COMBO", "required": true, "options": ["linear", "ease_in", "ease_out", "ease_in_out"]},
    },
    outputs: ["image"],
    outputNode: true,
  },
  LUT: {
    family: "video-look",
    frames: [{"name": "frames", "required": true}],
    sounds: [],
    widgets: {
      "lut_file": {"type": "COMBO", "required": true, "fileList": true},
      "strength": {"type": "FLOAT", "required": true, "min": 0.0, "max": 1.0},
    },
    outputs: ["image"],
    outputNode: true,
  },
  SaveAudioOpus: {
    family: "media-sound",
    frames: [],
    sounds: [{"name": "audio", "required": true}],
    widgets: {
      "filename_prefix": {"type": "STRING", "required": true},
      "quality": {"type": "COMBO", "required": true, "options": ["64k", "96k", "128k", "192k", "320k"]},
    },
    outputs: [],
    outputNode: true,
  },
  SlitScan: {
    family: "video-time",
    frames: [{"name": "frames", "required": true}],
    sounds: [],
    widgets: {
      "delay": {"type": "FLOAT", "required": true, "min": 0.0, "max": 4.0},
      "axis": {"type": "COMBO", "required": true, "options": ["horizontal", "vertical"]},
      "wrap": {"type": "BOOLEAN", "required": true},
    },
    outputs: ["image"],
    outputNode: true,
  },
  SpeedRamp: {
    family: "video-time",
    frames: [{"name": "frames", "required": true}],
    sounds: [],
    widgets: {
      "mode": {"type": "COMBO", "required": true, "options": ["constant", "ramp_in", "ramp_out", "ramp_in_out"]},
      "speed": {"type": "FLOAT", "required": true, "min": 0.05, "max": 10.0},
      "start_speed": {"type": "FLOAT", "required": true, "min": 0.05, "max": 10.0},
      "interpolation": {"type": "COMBO", "required": true, "options": ["nearest", "blend"]},
    },
    outputs: ["image"],
    outputNode: true,
  },
  SplitAudioChannels: {
    family: "sound-effects",
    frames: [],
    sounds: [{"name": "audio", "required": true}],
    widgets: {},
    outputs: ["audio", "audio"],
    outputNode: false,
  },
  Stabilize: {
    family: "video-stabilize",
    frames: [{"name": "frames", "required": true}],
    sounds: [],
    widgets: {
      "smoothing": {"type": "FLOAT", "required": true, "min": 0.0, "max": 0.99},
      "edge_mode": {"type": "COMBO", "required": true, "options": ["crop", "border"]},
      "crop_pad": {"type": "FLOAT", "required": true, "min": 0.0, "max": 0.3},
    },
    outputs: ["image"],
    outputNode: true,
  },
  TemporalMotionBlur: {
    family: "video-time",
    frames: [{"name": "frames", "required": true}],
    sounds: [],
    widgets: {
      "radius": {"type": "INT", "required": true, "min": 1, "max": 12},
      "falloff": {"type": "COMBO", "required": true, "options": ["uniform", "linear", "gaussian"]},
    },
    outputs: ["image"],
    outputNode: true,
  },
  TextClip: {
    family: "video-text",
    frames: [],
    sounds: [],
    widgets: {
      "text": {"type": "STRING", "required": true},
      "width": {"type": "INT", "required": true, "min": 64, "max": 4096},
      "height": {"type": "INT", "required": true, "min": 64, "max": 4096},
      "frame_count": {"type": "INT", "required": true, "min": 1, "max": 10000},
      "font_size": {"type": "INT", "required": true, "min": 8, "max": 512},
      "color": {"type": "STRING", "required": true},
      "bg_color": {"type": "STRING", "required": true},
      "align": {"type": "COMBO", "required": true, "options": ["center", "left", "right"]},
      "v_align": {"type": "COMBO", "required": true, "options": ["middle", "top", "bottom"]},
      "padding": {"type": "FLOAT", "required": true, "min": 0.0, "max": 0.4},
      "line_spacing": {"type": "FLOAT", "required": true, "min": 0.8, "max": 2.5},
    },
    outputs: ["image"],
    outputNode: false,
  },
  ThreeWayCC: {
    family: "video-look",
    frames: [{"name": "image", "required": true}],
    sounds: [],
    widgets: {
      "lift_r": {"type": "FLOAT", "required": true, "min": -0.5, "max": 0.5},
      "lift_g": {"type": "FLOAT", "required": true, "min": -0.5, "max": 0.5},
      "lift_b": {"type": "FLOAT", "required": true, "min": -0.5, "max": 0.5},
      "gamma_r": {"type": "FLOAT", "required": true, "min": 0.1, "max": 4.0},
      "gamma_g": {"type": "FLOAT", "required": true, "min": 0.1, "max": 4.0},
      "gamma_b": {"type": "FLOAT", "required": true, "min": 0.1, "max": 4.0},
      "gain_r": {"type": "FLOAT", "required": true, "min": 0.0, "max": 4.0},
      "gain_g": {"type": "FLOAT", "required": true, "min": 0.0, "max": 4.0},
      "gain_b": {"type": "FLOAT", "required": true, "min": 0.0, "max": 4.0},
    },
    outputs: ["image"],
    outputNode: true,
  },
  TimeDisplacement: {
    family: "video-time",
    frames: [{"name": "frames", "required": true}],
    sounds: [],
    widgets: {
      "strength": {"type": "FLOAT", "required": true, "min": 0.0, "max": 30.0},
      "noise_scale": {"type": "FLOAT", "required": true, "min": 8.0, "max": 400.0},
      "wrap": {"type": "BOOLEAN", "required": true},
      "seed": {"type": "INT", "required": true, "min": 0, "max": 2147483647},
    },
    outputs: ["image"],
    outputNode: true,
  },
  Transition: {
    family: "video-join",
    frames: [{"name": "clip_a", "required": true}, {"name": "clip_b", "required": true}],
    sounds: [],
    widgets: {
      "style": {"type": "COMBO", "required": true, "options": ["dissolve", "whip_pan_left", "whip_pan_right", "zoom_in", "zoom_out", "glitch", "light_leak"]},
      "duration": {"type": "INT", "required": true, "min": 1, "max": 240},
      "curve": {"type": "COMBO", "required": true, "options": ["linear", "ease_in_out", "ease_in", "ease_out"]},
    },
    outputs: ["image"],
    outputNode: true,
  },
  TrimAudioDuration: {
    family: "sound-effects",
    frames: [],
    sounds: [{"name": "audio", "required": true}],
    widgets: {
      "start_index": {"type": "FLOAT", "required": true, "min": -18446744073709551615, "max": 18446744073709551615},
      "duration": {"type": "FLOAT", "required": true, "min": 0.0},
    },
    outputs: ["audio"],
    outputNode: false,
  },
  VideoCrossfade: {
    family: "video-join",
    frames: [{"name": "clip_a", "required": true}, {"name": "clip_b", "required": true}],
    sounds: [],
    widgets: {
      "duration": {"type": "INT", "required": true, "min": 1, "max": 2400},
      "curve": {"type": "COMBO", "required": true, "options": ["linear", "ease_in_out", "ease_in", "ease_out"]},
      "trim_in_a": {"type": "INT", "required": true, "min": 0, "max": 100000},
      "trim_out_a": {"type": "INT", "required": true, "min": -1, "max": 100000},
      "trim_in_b": {"type": "INT", "required": true, "min": 0, "max": 100000},
      "trim_out_b": {"type": "INT", "required": true, "min": -1, "max": 100000},
    },
    outputs: ["image"],
    outputNode: true,
  },
  VideoReverse: {
    family: "video-time",
    frames: [{"name": "frames", "required": true}],
    sounds: [],
    widgets: {
      "mode": {"type": "COMBO", "required": true, "options": ["reverse", "ping_pong"]},
    },
    outputs: ["image"],
    outputNode: true,
  },
  VideoSilenceCut: {
    family: "sound-effects",
    frames: [{"name": "frames", "required": true}],
    sounds: [{"name": "audio", "required": true}],
    widgets: {
      "fps": {"type": "FLOAT", "required": true, "min": 1.0, "max": 120.0},
      "threshold_db": {"type": "FLOAT", "required": true, "min": -80.0, "max": 0.0},
      "min_silence_ms": {"type": "INT", "required": true, "min": 20, "max": 5000},
      "keep_padding_ms": {"type": "INT", "required": true, "min": 0, "max": 2000},
    },
    outputs: ["image", "audio"],
    outputNode: false,
  },
  VideoTrim: {
    family: "video-time",
    frames: [{"name": "frames", "required": true}],
    sounds: [],
    widgets: {
      "start": {"type": "INT", "required": true, "min": 0, "max": 10000},
      "end": {"type": "INT", "required": true, "min": -1, "max": 10000},
    },
    outputs: ["image"],
    outputNode: true,
  },
}
