/** Words people say that ambientCG's tags do not carry, mapped to words they do.
 *  Keys are lower-case single words; values are the tag words to search instead. */
export const SYNONYMS: Record<string, string[]> = {
  wooden: ['wood'],
  timber: ['wood'],
  floorboards: ['wood', 'planks'],
  floorboard: ['wood', 'planks'],
  parquet: ['wood', 'floor'],
  stone: ['rock'],
  stones: ['rock'],
  cobble: ['cobblestone'],
  steel: ['metal'],
  iron: ['metal', 'rust'],
  rusty: ['rust'],
  rusted: ['rust'],
  cloth: ['fabric'],
  textile: ['fabric'],
  linen: ['fabric'],
  denim: ['fabric'],
  cement: ['concrete'],
  plaster: ['plaster', 'wall'],
  tile: ['tiles'],
  tiled: ['tiles'],
  ceramic: ['tiles'],
  lawn: ['grass'],
  turf: ['grass'],
  soil: ['ground', 'dirt'],
  earth: ['ground', 'dirt'],
  mud: ['ground', 'dirt'],
  sandy: ['sand'],
  snowy: ['snow'],
  icy: ['ice'],
  golden: ['gold'],
  marbled: ['marble'],
  leathery: ['leather'],
  paper: ['paper'],
  cardboard: ['cardboard'],
  brickwork: ['bricks'],
  bricks: ['bricks', 'brick'],
  brick: ['bricks', 'brick'],
}
