// Auto-generated beginner-friendly descriptions for all ComfyUI nodes.
// Used as fallback when the /object_info API returns no description.
export const NODE_DESCRIPTIONS: Record<string, string> = {
  'APG': 'Applies adaptive projected guidance to fine-tune how the model follows your prompt during image generation.',
  'AddNoise': 'Adds noise to the AI\'s internal image data at a specified level for testing purposes.',
  'AddTextPrefix': 'Adds a prefix string to the beginning of each text entry in a dataset.',
  'AddTextSuffix': 'Adds a suffix string to the end of each text entry in a dataset.',
  'AdjustBrightness': 'Adjusts the brightness of images by a given factor.',
  'AdjustContrast': 'Adjusts the contrast of images by a given factor.',
  'AlignYourStepsScheduler': 'Creates an optimized step schedule for image generation based on the chosen model type.',
  'AudioAdjustVolume': 'Adjusts the volume level of an audio clip up or down.',
  'AudioConcat': 'Joins two audio clips together into one continuous audio track.',
  'AudioEncoderEncode': 'Converts audio into encoded data that can be used as input for generation models.',
  'AudioEncoderLoader': 'Loads an audio encoder model from disk for processing audio inputs.',
  'AudioEqualizer3Band': 'Adjusts low, mid, and high frequency levels in an audio clip.',
  'AudioMerge': 'Merges two audio clips together using a chosen blending method.',
  'BasicGuider': 'Creates a basic guide that steers image generation using a model and text guidance.',
  'BasicScheduler': 'Creates a step schedule controlling how the image is refined during generation.',
  'BatchImagesNode': 'Combines multiple images into a single batch for processing together.',
  'BatchLatentsNode': 'Combines multiple sets of the AI\'s internal image data into one batch.',
  'BatchMasksNode': 'Combines multiple masks into a single batch for processing together.',
  'BetaSamplingScheduler': 'Creates a beta-distribution step schedule for controlling image generation refinement.',
  'BriaImageEditNode': 'Edits an image using Bria\'s cloud API based on your text prompt.',
  'BriaRemoveImageBackground': 'Removes the background from an image using Bria\'s cloud API.',
  'BriaRemoveVideoBackground': 'Removes the background from a video using Bria\'s cloud API.',
  'ByteDanceFirstLastFrameNode': 'Generates a video from first and last frame images using ByteDance\'s cloud API.',
  'ByteDanceImageNode': 'Generates an image from a text prompt using ByteDance\'s cloud API.',
  'ByteDanceImageReferenceNode': 'Generates a video from reference images using ByteDance\'s cloud API.',
  'ByteDanceImageToVideoNode': 'Converts a still image into a video using ByteDance\'s cloud API.',
  'ByteDanceSeedreamNode': 'Generates an image from a text prompt using ByteDance Seedream models via cloud API.',
  'ByteDanceTextToVideoNode': 'Generates a video from a text prompt using ByteDance\'s cloud API.',
  'CFGGuider': 'Creates a guide that steers generation using positive and negative text guidance with adjustable strength.',
  'CFGNorm': 'Applies guidance normalization to the model to stabilize image generation quality.',
  'CFGZeroStar': 'Applies CFG-Zero* guidance correction to improve image generation consistency.',
  'CLIPAttentionMultiply': 'Adjusts attention weights inside the text encoder for experimental fine-tuning.',
  'CLIPLoader': 'Loads a text encoder model from disk for converting text into generation guidance.',
  'CLIPMergeAdd': 'Combines two text encoder models by adding their weights together.',
  'CLIPMergeSimple': 'Blends two text encoder models together at a specified ratio.',
  'CLIPMergeSubtract': 'Subtracts one text encoder model\'s weights from another with a multiplier.',
  'CLIPSave': 'Saves a text encoder model to disk as a file.',
  'CLIPSetLastLayer': 'Sets which layer of the text encoder to use as the final output.',
  'CLIPTextEncode': 'Converts your text prompt into text guidance that directs image generation.',
  'CLIPTextEncodeControlnet': 'Converts text into text guidance formatted for use with ControlNet.',
  'CLIPTextEncodeFlux': 'Converts text prompts into text guidance formatted for Flux models.',
  'CLIPTextEncodeHiDream': 'Converts text prompts into text guidance formatted for HiDream models.',
  'CLIPTextEncodeHunyuanDiT': 'Converts text prompts into text guidance formatted for HunyuanDiT models.',
  'CLIPTextEncodeKandinsky5': 'Converts text prompts into text guidance formatted for Kandinsky 5 models.',
  'CLIPTextEncodeLumina2': 'Converts text prompts into text guidance formatted for Lumina2 models.',
  'CLIPTextEncodePixArtAlpha': 'Converts text prompts into text guidance formatted for PixArt Alpha models.',
  'CLIPTextEncodeSD3': 'Converts text prompts into text guidance formatted for SD3 models.',
  'CLIPTextEncodeSDXL': 'Converts text prompts into text guidance formatted for SDXL models with resolution settings.',
  'CLIPTextEncodeSDXLRefiner': 'Converts text into text guidance formatted for the SDXL refiner stage.',
  'CLIPVisionEncode': 'Converts an image into visual guidance data using a vision encoder model.',
  'CLIPVisionLoader': 'Loads a vision encoder model from disk for analyzing images.',
  'Canny': 'Detects edges in an image to create a line-art outline.',
  'CaseConverter': 'Converts text between uppercase, lowercase, and other case formats.',
  'CenterCropImages': 'Crops images to specified dimensions from their center point.',
  'CheckpointLoader': 'Loads an AI model checkpoint with a configuration file (deprecated, use Load Checkpoint instead).',
  'CheckpointLoaderSimple': 'Loads an AI model checkpoint file containing the model, text encoder, and image decoder.',
  'CheckpointSave': 'Saves the current model, text encoder, and image decoder as a checkpoint file.',
  'ChromaRadianceOptions': 'Configures Chroma Radiance model settings for preserving details during generation.',
  'ColorToRGBInt': 'Converts a color value into separate red, green, and blue integer values.',
  'CombineHooks2': 'Combines two hook modifications together to apply them simultaneously.',
  'CombineHooks4': 'Combines four hook modifications together to apply them simultaneously.',
  'CombineHooks8': 'Combines eight hook modifications together to apply them simultaneously.',
  'ComfyMathExpression': 'Evaluates a math expression and returns the result as a number.',
  'ComfySwitchNode': 'Routes data to one of two outputs based on a true/false switch.',
  'ConditioningAverage': 'Blends two sets of text guidance together at a specified strength ratio.',
  'ConditioningCombine': 'Combines two sets of text guidance so both influence the generated image.',
  'ConditioningConcat': 'Concatenates two sets of text guidance together in sequence.',
  'ConditioningSetArea': 'Restricts text guidance to apply only within a specific rectangular area.',
  'ConditioningSetAreaPercentage': 'Restricts text guidance to a specific area defined by percentage coordinates.',
  'ConditioningSetAreaPercentageVideo': 'Restricts text guidance to a specific area in video frames using percentage coordinates.',
  'ConditioningSetAreaStrength': 'Adjusts the influence strength of area-restricted text guidance.',
  'ConditioningSetDefaultCombine': 'Sets a default text guidance to combine with the primary guidance.',
  'ConditioningSetMask': 'Applies a mask to limit where text guidance takes effect in the image.',
  'ConditioningSetProperties': 'Sets strength and area properties on a text guidance input.',
  'ConditioningSetPropertiesAndCombine': 'Sets properties on text guidance and combines it with another guidance set.',
  'ConditioningSetTimestepRange': 'Limits text guidance to apply only during a specific range of generation steps.',
  'ConditioningStableAudio': 'Prepares text guidance with timing controls for Stable Audio generation.',
  'ConditioningTimestepsRange': 'Defines a time range for controlling when effects are applied during generation.',
  'ConditioningZeroOut': 'Clears all text guidance content, creating an empty guidance signal.',
  'ContextWindowsManual': 'Configures manual context window settings for processing long video sequences.',
  'ControlNetApply': 'Applies a ControlNet model to guide image generation using a reference image (old version).',
  'ControlNetApplyAdvanced': 'Applies a ControlNet model to steer image generation using a reference image.',
  'ControlNetApplySD3': 'Applies a ControlNet model with an image decoder for SD3-compatible guided generation.',
  'ControlNetInpaintingAliMamaApply': 'Applies an inpainting ControlNet to fill in masked areas of an image.',
  'ControlNetLoader': 'Loads a ControlNet model from disk for guided image generation.',
  'CosmosImageToVideoLatent': 'Prepares an image as the AI\'s internal video data for Cosmos video generation.',
  'CosmosPredict2ImageToVideoLatent': 'Prepares an image as the AI\'s internal video data for Cosmos Predict2 generation.',
  'CreateHookKeyframe': 'Creates a single keyframe controlling hook effect strength at a specific point.',
  'CreateHookKeyframesFromFloats': 'Creates multiple hook keyframes from a list of strength values.',
  'CreateHookKeyframesInterpolated': 'Creates smoothly interpolated hook keyframes between start and end strength values.',
  'CreateHookLora': 'Creates a hook that applies a LoRA style adjustment to both model and text encoder.',
  'CreateHookLoraModelOnly': 'Creates a hook that applies a LoRA style adjustment to the model only.',
  'CreateHookModelAsLora': 'Creates a hook that uses a full model checkpoint as a style adjustment.',
  'CreateHookModelAsLoraModelOnly': 'Creates a hook using a model checkpoint as a style adjustment for the model only.',
  'CreateList': 'Creates a list from multiple inputs for batch processing.',
  'CreateVideo': 'Combines a sequence of images into a video at the specified frame rate.',
  'CropByBBoxes': 'Crops regions from an image using bounding box coordinates.',
  'CropMask': 'Crops a mask to a specified rectangular region.',
  'CustomCombo': 'Provides a dropdown menu that outputs the selected choice as text or a number.',
  'DiffControlNetLoader': 'Loads a differential ControlNet model that builds on an existing AI model.',
  'DifferentialDiffusion': 'Enables variable-strength generation across different regions of an image using a mask.',
  'DiffusersLoader': 'Loads a Diffusers-format AI model from disk (deprecated).',
  'DisableNoise': 'Creates a no-noise setting for deterministic image generation without randomness.',
  'DualCFGGuider': 'Creates a guide using two separate text guidance inputs for dual-prompt generation.',
  'DualCLIPLoader': 'Loads two text encoder models together, often needed for advanced model architectures.',
  'EasyCache': 'Speeds up generation by caching and reusing model computations between steps.',
  'ElevenLabsAudioIsolation': 'Isolates vocals from background noise in audio using ElevenLabs cloud API.',
  'ElevenLabsInstantVoiceClone': 'Creates a cloned voice from audio samples using ElevenLabs cloud API.',
  'ElevenLabsSpeechToSpeech': 'Converts speech audio into a different voice using ElevenLabs cloud API.',
  'ElevenLabsSpeechToText': 'Transcribes speech audio into text using ElevenLabs cloud API.',
  'ElevenLabsTextToDialogue': 'Generates multi-speaker dialogue audio from text using ElevenLabs cloud API.',
  'ElevenLabsTextToSoundEffects': 'Generates sound effects from a text description using ElevenLabs cloud API.',
  'ElevenLabsTextToSpeech': 'Converts text into spoken audio using ElevenLabs cloud API.',
  'ElevenLabsVoiceSelector': 'Selects a voice from available ElevenLabs voices for speech generation.',
  'EmptyAceStep1.5LatentAudio': 'Creates blank AI internal audio data for AceStep 1.5 music generation.',
  'EmptyAceStepLatentAudio': 'Creates blank AI internal audio data for AceStep 1.0 music generation.',
  'EmptyAudio': 'Creates a silent audio clip with specified duration and sample rate.',
  'EmptyChromaRadianceLatentImage': 'Creates blank AI internal image data sized for Chroma Radiance models.',
  'EmptyCosmosLatentVideo': 'Creates blank AI internal video data sized for Cosmos video generation.',
  'EmptyFlux2LatentImage': 'Creates blank AI internal image data sized for Flux 2 models.',
  'EmptyHunyuanImageLatent': 'Creates blank AI internal image data sized for Hunyuan image models.',
  'EmptyHunyuanLatentVideo': 'Creates blank AI internal video data sized for HunyuanVideo 1.0.',
  'EmptyHunyuanVideo15Latent': 'Creates blank AI internal video data sized for HunyuanVideo 1.5.',
  'EmptyImage': 'Creates a blank image with specified width, height, and batch size.',
  'EmptyLTXVLatentVideo': 'Creates blank AI internal video data sized for LTXV video models.',
  'EmptyLatentAudio': 'Creates blank AI internal audio data for audio generation.',
  'EmptyLatentHunyuan3Dv2': 'Creates blank AI internal 3D data for Hunyuan 3D v2 generation.',
  'EmptyLatentImage': 'Creates blank AI internal image data at your chosen dimensions to start generation.',
  'EmptyMochiLatentVideo': 'Creates blank AI internal video data sized for Mochi video models.',
  'EmptyQwenImageLayeredLatentImage': 'Creates blank layered AI internal image data for Qwen image models.',
  'EmptySD3LatentImage': 'Creates blank AI internal image data sized for SD3 models.',
  'Epsilon Scaling': 'Adjusts the noise prediction scaling factor of the model during generation.',
  'ExponentialScheduler': 'Creates an exponentially decreasing step schedule for image generation.',
  'ExtendIntermediateSigmas': 'Adds extra refinement steps at a specific point in the generation schedule.',
  'FaceSwap': 'Puts the face from one photo into another picture.',
  'FeatherMask': 'Softens the edges of a mask with a gradual fade on each side.',
  'FlipSigmas': 'Reverses the order of the generation step schedule.',
  'Flux2MaxImageNode': 'Generates a high-quality image using the Flux.2 Max cloud API.',
  'Flux2ProImageNode': 'Generates a professional image using the Flux.2 Pro cloud API.',
  'Flux2Scheduler': 'Creates a step schedule optimized for Flux 2 model generation.',
  'FluxDisableGuidance': 'Disables prompt guidance for a Flux model text guidance input.',
  'FluxGuidance': 'Sets the prompt guidance strength for Flux model generation.',
  'FluxKVCache': 'Enables key-value caching to speed up Flux model generation.',
  'FluxKontextImageScale': 'Scales an image to the correct size for Flux Kontext processing.',
  'FluxKontextMaxImageNode': 'Edits or generates images using Flux Kontext Max cloud API with reference images.',
  'FluxKontextMultiReferenceLatentMethod': 'Sets how multiple reference images are combined during Flux Kontext generation.',
  'FluxKontextProImageNode': 'Edits or generates images using Flux Kontext Pro cloud API with reference images.',
  'FluxProExpandNode': 'Expands an image outward beyond its borders using Flux cloud API.',
  'FluxProFillNode': 'Fills in masked areas of an image using Flux cloud API inpainting.',
  'FluxProUltraImageNode': 'Generates an ultra-high-quality image using Flux 1.1 Pro Ultra cloud API.',
  'FreSca': 'Applies frequency-based scaling to adjust detail levels during generation.',
  'FreeU': 'Improves image quality by adjusting internal model feature scaling (version 1).',
  'FreeU_V2': 'Improves image quality by adjusting internal model feature scaling (version 2).',
  'GITSScheduler': 'Creates a GITS-optimized step schedule for faster image generation.',
  'GLIGENLoader': 'Loads a GLIGEN model for placing objects at specific positions in images.',
  'GLIGENTextBoxApply': 'Places text-described objects into specific bounding box regions of an image.',
  'GLSLShader': 'Applies a custom GPU shader effect to images using GLSL code.',
  'GeminiImage2Node': 'Generates an image using Google Gemini Nano Banana Pro cloud API.',
  'GeminiImageNode': 'Generates an image using Google Gemini Nano Banana cloud API.',
  'GeminiInputFiles': 'Loads input files to send as context to Google Gemini cloud API.',
  'GeminiNanoBanana2': 'Generates an image using Google Gemini Nano Banana 2 cloud API.',
  'GeminiNode': 'Generates text responses using Google Gemini cloud API.',
  'GenerateTracks': 'Creates motion tracking paths for guiding object movement in video generation.',
  'GetImageSize': 'Returns the width and height dimensions of an image.',
  'GetVideoComponents': 'Splits a video into its separate image frames and audio track.',
  'GrokImageEditNode': 'Edits an image based on a text prompt using Grok cloud API.',
  'GrokImageNode': 'Generates an image from a text prompt using Grok cloud API.',
  'GrokVideoEditNode': 'Edits a video based on a text prompt using Grok cloud API.',
  'GrokVideoNode': 'Generates a video from a text prompt using Grok cloud API.',
  'GrowMask': 'Expands or shrinks a mask by a specified number of pixels.',
  'HitPawGeneralImageEnhance': 'Upscales and enhances image quality using HitPaw cloud API.',
  'HitPawVideoEnhance': 'Upscales and enhances video quality using HitPaw cloud API.',
  'Hunyuan3Dv2Conditioning': 'Prepares visual guidance from an encoded image for Hunyuan 3D v2 generation.',
  'Hunyuan3Dv2ConditioningMultiView': 'Prepares multi-view guidance for generating 3D models with Hunyuan 3D v2.',
  'HunyuanImageToVideo': 'Converts a still image into a video using the Hunyuan video model.',
  'HunyuanRefinerLatent': 'Refines the AI\'s internal image data using the Hunyuan refiner for improved quality.',
  'HunyuanVideo15ImageToVideo': 'Converts a still image into a video using HunyuanVideo 1.5 model.',
  'HunyuanVideo15LatentUpscaleWithModel': 'Upscales the AI\'s internal video data using a dedicated upscale model.',
  'HunyuanVideo15SuperResolution': 'Increases video resolution and detail using HunyuanVideo 1.5 super-resolution.',
  'HyperTile': 'Speeds up generation by processing the image in smaller tile sections.',
  'HypernetworkLoader': 'Loads a hypernetwork style modifier and applies it to the AI model.',
  'IdeogramV1': 'Generates an image from a text prompt using Ideogram V1 cloud API.',
  'IdeogramV2': 'Generates an image from a text prompt using Ideogram V2 cloud API.',
  'IdeogramV3': 'Generates an image from a text prompt using Ideogram V3 cloud API.',
  'ImageAddNoise': 'Adds random visual noise to an image at the specified strength.',
  'ImageBatch': 'Combines two images into a single batch for processing together.',
  'ImageBlend': 'Blends two images together at a specified mix ratio.',
  'ImageBlur': 'Applies a blur effect to soften an image.',
  'ImageColorToMask': 'Creates a mask from all pixels matching a specific color in an image.',
  'ImageCompare': 'Displays images side by side for visual comparison.',
  'ImageCompositeMasked': 'Pastes one image onto another at a specified position using a mask.',
  'ImageCrop': 'Crops an image to specified dimensions (deprecated, use Image Crop V2).',
  'ImageCropV2': 'Crops an image using a bounding box region.',
  'ImageDeduplication': 'Removes duplicate or very similar images from a batch.',
  'ImageFlip': 'Flips an image horizontally, vertically, or both.',
  'ImageFromBatch': 'Extracts specific images from a batch by index position.',
  'ImageGrid': 'Arranges multiple images into a grid layout with specified columns.',
  'ImageInvert': 'Inverts all colors in an image, creating a negative effect.',
  'ImageMergeTileList': 'Reassembles a list of image tiles back into a single full image.',
  'ImageOnlyCheckpointLoader': 'Loads a video model checkpoint for image-to-video generation workflows.',
  'ImageOnlyCheckpointSave': 'Saves a video model with its vision encoder and image decoder as a checkpoint.',
  'ImagePadForOutpaint': 'Adds padding around an image with a mask for extending the image outward.',
  'ImageQuantize': 'Reduces the number of colors in an image with optional dithering.',
  'ImageRGBToYUV': 'Converts an image from RGB color space to YUV brightness and color channels.',
  'ImageRotate': 'Rotates an image by a preset angle.',
  'ImageScale': 'Resizes an image to specific width and height dimensions.',
  'ImageScaleBy': 'Resizes an image by a multiplier factor.',
  'ImageScaleToMaxDimension': 'Resizes an image so its largest side matches the specified size.',
  'ImageScaleToTotalPixels': 'Resizes an image to approximately the specified megapixel count.',
  'ImageSharpen': 'Sharpens an image to enhance fine details and edges.',
  'ImageStitch': 'Joins two images side by side or stacked vertically into one image.',
  'ImageToMask': 'Converts a color channel of an image into a mask.',
  'ImageUpscaleWithModel': 'Enlarges an image using a dedicated AI upscaling model for high-quality results.',
  'ImageYUVToRGB': 'Converts YUV brightness and color channel images back to a standard RGB image.',
  'InpaintModelConditioning': 'Prepares text guidance and a masked image for inpainting with dedicated inpaint models.',
  'InstructPixToPixConditioning': 'Prepares text guidance and an image for instruction-based image editing.',
  'InvertMask': 'Inverts a mask, swapping selected and unselected areas.',
  'JoinAudioChannels': 'Combines separate left and right audio tracks into a single stereo audio clip.',
  'JoinImageWithAlpha': 'Combines an image with a transparency mask to create a transparent image.',
  'KSampler': 'Generates images from a model using a seed, step count, and the AI\'s internal image data.',
  'KSamplerAdvanced': 'Generates images with extra control over noise, seed, and sampling steps.',
  'KSamplerSelect': 'Selects which sampling algorithm to use for image generation.',
  'Kandinsky5ImageToVideo': 'Converts an image into a video using the Kandinsky 5 video model.',
  'KarrasScheduler': 'Creates a noise schedule using the Karras method for custom image generation.',
  'KlingAvatarNode': 'Creates a talking avatar video from a photo and audio using Kling API.',
  'KlingCameraControlI2VNode': 'Turns an image into a video with camera movement controls using Kling API.',
  'KlingCameraControlT2VNode': 'Creates a video from text with camera movement controls using Kling API.',
  'KlingCameraControls': 'Defines camera movement type and direction for Kling video generation.',
  'KlingDualCharacterVideoEffectNode': 'Creates a video effect combining two character images into a scene using Kling API.',
  'KlingFirstLastFrameNode': 'Creates a video from first and last frame images using Kling 3.0 API.',
  'KlingImage2VideoNode': 'Turns a starting image into a video clip using Kling API.',
  'KlingImageGenerationNode': 'Generates an image from a text prompt using Kling 3.0 API.',
  'KlingImageToVideoWithAudio': 'Turns an image into a video with audio using Kling 2.6 API.',
  'KlingLipSyncAudioToVideoNode': 'Syncs lip movements in a video to match an audio file using Kling API.',
  'KlingLipSyncTextToVideoNode': 'Syncs lip movements in a video to match spoken text using Kling API.',
  'KlingMotionControl': 'Creates a video with guided motion from a reference image and video using Kling.',
  'KlingOmniProEditVideoNode': 'Edits an existing video based on a text prompt using Kling 3.0 Omni.',
  'KlingOmniProFirstLastFrameNode': 'Creates a video from first and last frames using Kling 3.0 Omni.',
  'KlingOmniProImageNode': 'Generates an image from a text prompt using Kling 3.0 Omni.',
  'KlingOmniProImageToVideoNode': 'Turns an image into a video using Kling 3.0 Omni API.',
  'KlingOmniProTextToVideoNode': 'Creates a video from a text description using Kling 3.0 Omni API.',
  'KlingOmniProVideoToVideoNode': 'Transforms an existing video based on a text prompt using Kling 3.0 Omni.',
  'KlingSingleImageVideoEffectNode': 'Applies a visual effect to an image and outputs a video using Kling API.',
  'KlingStartEndFrameNode': 'Creates a video that transitions between a start and end image using Kling.',
  'KlingTextToVideoNode': 'Creates a video from a text description using Kling API.',
  'KlingTextToVideoWithAudio': 'Creates a video with audio from a text prompt using Kling 2.6 API.',
  'KlingVideoExtendNode': 'Extends an existing video to make it longer using Kling API.',
  'KlingVideoNode': 'Generates a video with optional audio using Kling 3.0 API.',
  'KlingVirtualTryOnNode': 'Places clothing from one image onto a person in another image using Kling.',
  'LTXAVTextEncoderLoader': 'Loads a text encoder model for LTXV audio-video generation.',
  'LTXVAddGuide': 'Adds a guide frame to steer LTXV video generation direction.',
  'LTXVAudioVAEDecode': 'Converts the AI\'s internal audio data back into a playable audio file.',
  'LTXVAudioVAEEncode': 'Converts an audio file into the AI\'s internal audio data for processing.',
  'LTXVAudioVAELoader': 'Loads an audio image decoder/encoder model for LTXV audio processing.',
  'LTXVConcatAVLatent': 'Combines video and audio internal data into a single synchronized stream.',
  'LTXVConditioning': 'Prepares text guidance with frame rate settings for LTXV video generation.',
  'LTXVCropGuides': 'Crops guide frames to match the size of the AI\'s internal image data.',
  'LTXVEmptyLatentAudio': 'Creates blank internal audio data as a starting point for audio generation.',
  'LTXVImgToVideo': 'Adds an image as a starting frame for LTXV video generation.',
  'LTXVImgToVideoInplace': 'Embeds a starting image directly into the AI\'s internal video data for LTXV.',
  'LTXVLatentUpsampler': 'Increases the resolution of the AI\'s internal video data using an upscale model.',
  'LTXVPreprocess': 'Prepares and compresses an image for use with LTXV video generation.',
  'LTXVScheduler': 'Creates a noise schedule with shift settings for LTXV video generation.',
  'LTXVSeparateAVLatent': 'Splits combined audio-video internal data into separate video and audio parts.',
  'LayerizeGraphicNode': 'Splits a flat graphic into a text-free background image plus structured text-layer data using Ideogram Layerize.',
  'LaplaceScheduler': 'Creates a noise schedule using the Laplace method for custom image generation.',
  'LatentAdd': 'Adds two sets of the AI\'s internal image data together.',
  'LatentApplyOperation': 'Applies a chosen operation to the AI\'s internal image data.',
  'LatentApplyOperationCFG': 'Applies an operation to the AI\'s internal image data during the generation process.',
  'LatentBatch': 'Combines two sets of the AI\'s internal image data into one batch.',
  'LatentBatchSeedBehavior': 'Controls how random seeds behave across batches of the AI\'s internal image data.',
  'LatentBlend': 'Blends two sets of the AI\'s internal image data together by a given ratio.',
  'LatentComposite': 'Pastes one set of the AI\'s internal image data onto another at a position.',
  'LatentCompositeMasked': 'Pastes one set of the AI\'s internal image data onto another using a mask.',
  'LatentConcat': 'Joins two sets of the AI\'s internal image data along a chosen dimension.',
  'LatentCrop': 'Crops the AI\'s internal image data to a specified width and height.',
  'LatentCut': 'Cuts a slice from the AI\'s internal image data along a chosen dimension.',
  'LatentCutToBatch': 'Slices the AI\'s internal image data into evenly sized batches.',
  'LatentFlip': 'Flips the AI\'s internal image data horizontally or vertically.',
  'LatentFromBatch': 'Extracts specific frames from a batch of the AI\'s internal image data.',
  'LatentInterpolate': 'Blends between two sets of the AI\'s internal image data using a ratio.',
  'LatentMultiply': 'Multiplies the AI\'s internal image data values by a given number.',
  'LatentOperationSharpen': 'Creates a sharpening operation to apply to the AI\'s internal image data.',
  'LatentOperationTonemapReinhard': 'Creates a tone mapping operation to balance brightness in the AI\'s internal image data.',
  'LatentRotate': 'Rotates the AI\'s internal image data by a specified angle.',
  'LatentSubtract': 'Subtracts one set of the AI\'s internal image data from another.',
  'LatentUpscale': 'Increases the resolution of the AI\'s internal image data to a specific size.',
  'LatentUpscaleBy': 'Increases the resolution of the AI\'s internal image data by a scale factor.',
  'LatentUpscaleModelLoader': 'Loads an upscale model for increasing the AI\'s internal image data resolution.',
  'LazyCache': 'Caches model computations to speed up repeated generation steps.',
  'Load3D': 'Loads a 3D model or animation file for use in the workflow.',
  'LoadAudio': 'Loads an audio file from disk for use in the workflow.',
  'LoadImage': 'Loads an image file from disk for use in the workflow.',
  'LoadImageDataSetFromFolder': 'Loads a folder of images as a training dataset.',
  'LoadImageMask': 'Loads an image and converts a chosen color channel into a mask.',
  'LoadImageOutput': 'Loads a previously generated image from the outputs folder.',
  'LoadImageTextDataSetFromFolder': 'Loads paired images and text descriptions from a folder as a dataset.',
  'LoadLatent': 'Loads previously saved AI internal image data from a file.',
  'LoadTrainingDataset': 'Loads a prepared training dataset for model fine-tuning.',
  'LoadVideo': 'Loads a video file from disk for use in the workflow.',
  'LoraLoader': 'Loads a LoRA file to adjust both the model and text encoder behavior.',
  'LoraLoaderBypass': 'Loads a LoRA file in bypass mode for debugging without applying changes.',
  'LoraLoaderBypassModelOnly': 'Loads a LoRA in bypass mode for model-only debugging.',
  'LoraLoaderModelOnly': 'Loads a LoRA file to adjust only the model behavior.',
  'LoraModelLoader': 'Loads a LoRA model and applies it with adjustable strength.',
  'LoraSave': 'Extracts and saves a LoRA file from the current model differences.',
  'LossGraphNode': 'Plots a training loss graph to visualize model learning progress.',
  'LotusConditioning': 'Creates text guidance settings for the Lotus depth estimation model.',
  'LtxvApiImageToVideo': 'Turns an image into a video using the LTXV cloud API.',
  'LtxvApiTextToVideo': 'Creates a video from a text description using the LTXV cloud API.',
  'LumaConceptsNode': 'Combines up to three style concepts for Luma video generation.',
  'LumaImageModifyNode': 'Modifies an existing image based on a text prompt using Luma API.',
  'LumaImageNode': 'Generates an image from a text description using Luma API.',
  'LumaImageToVideoNode': 'Turns an image into a video using Luma API.',
  'LumaReferenceNode': 'Provides a reference image to guide Luma image generation style.',
  'LumaVideoNode': 'Creates a video from a text description using Luma API.',
  'MagnificImageRelightNode': 'Changes the lighting of an image using a text prompt via Magnific API.',
  'MagnificImageSkinEnhancerNode': 'Enhances skin details and texture in portrait images using Magnific API.',
  'MagnificImageStyleTransferNode': 'Applies the visual style of one image onto another using Magnific API.',
  'MagnificImageUpscalerCreativeNode': 'Upscales an image with creative AI enhancement using Magnific API.',
  'MagnificImageUpscalerPreciseV2Node': 'Upscales an image with precise detail preservation using Magnific API.',
  'Mahiro': 'Applies positive-biased guidance to improve model output quality.',
  'MakeTrainingDataset': 'Converts images and text into a prepared dataset for model training.',
  'ManualSigmas': 'Defines a custom noise schedule by manually entering sigma values.',
  'MaskComposite': 'Combines two masks together at a specified position.',
  'MaskPreview': 'Displays a preview of a mask to check its appearance.',
  'MaskToImage': 'Converts a mask into a regular image for viewing or further processing.',
  'MergeImageLists': 'Combines multiple image lists into a single unified list.',
  'MergeTextLists': 'Combines multiple text lists into a single unified list.',
  'MeshyAnimateModelNode': 'Animates a rigged 3D model with a chosen action using Meshy API.',
  'MeshyImageToModelNode': 'Creates a 3D model from a single image using Meshy API.',
  'MeshyMultiImageToModelNode': 'Creates a 3D model from multiple images using Meshy API.',
  'MeshyRefineNode': 'Refines a draft 3D model to improve quality using Meshy API.',
  'MeshyRigModelNode': 'Adds a skeleton rig to a 3D model for animation using Meshy API.',
  'MeshyTextToModelNode': 'Creates a 3D model from a text description using Meshy API.',
  'MeshyTextureNode': 'Applies textures and materials to a 3D model using Meshy API.',
  'MinimaxHailuoVideoNode': 'Creates a video from a text prompt using MiniMax Hailuo API.',
  'MinimaxImageToVideoNode': 'Turns an image into a video using MiniMax API.',
  'MinimaxTextToVideoNode': 'Creates a video from a text description using MiniMax API.',
  'ModelComputeDtype': 'Sets the numerical precision type for model computations.',
  'ModelMergeAdd': 'Combines two models by adding their weights together.',
  'ModelMergeAuraflow': 'Merges two Auraflow models with per-layer weight control.',
  'ModelMergeBlocks': 'Merges two models with separate weight controls for each block.',
  'ModelMergeCosmos14B': 'Merges two Cosmos 14B models with per-layer weight control.',
  'ModelMergeCosmos7B': 'Merges two Cosmos 7B models with per-layer weight control.',
  'ModelMergeCosmosPredict2_14B': 'Merges two Cosmos Predict2 14B models with per-layer weight control.',
  'ModelMergeCosmosPredict2_2B': 'Merges two Cosmos Predict2 2B models with per-layer weight control.',
  'ModelMergeFlux1': 'Merges two Flux.1 models with per-layer weight control.',
  'ModelMergeLTXV': 'Merges two LTXV models with per-layer weight control.',
  'ModelMergeMochiPreview': 'Merges two Mochi Preview models with per-layer weight control.',
  'ModelMergeQwenImage': 'Merges two Qwen image models with per-layer weight control.',
  'ModelMergeSD1': 'Merges two Stable Diffusion 1.x models with per-layer weight control.',
  'ModelMergeSD2': 'Merges two Stable Diffusion 2.x models with per-layer weight control.',
  'ModelMergeSD35_Large': 'Merges two Stable Diffusion 3.5 Large models with per-layer weight control.',
  'ModelMergeSD3_2B': 'Merges two Stable Diffusion 3 2B models with per-layer weight control.',
  'ModelMergeSDXL': 'Merges two SDXL models with per-layer weight control.',
  'ModelMergeSimple': 'Merges two models together using a simple ratio blend.',
  'ModelMergeSubtract': 'Subtracts one model\'s weights from another with adjustable strength.',
  'ModelMergeWAN2_1': 'Merges two WAN 2.1 models with per-layer weight control.',
  'ModelPatchLoader': 'Loads a model patch file to modify model behavior.',
  'ModelSamplingAuraFlow': 'Adjusts the noise sampling settings for AuraFlow models.',
  'ModelSamplingContinuousEDM': 'Adjusts continuous noise sampling settings for EDM-style models.',
  'ModelSamplingContinuousV': 'Adjusts continuous noise sampling settings for V-prediction models.',
  'ModelSamplingDiscrete': 'Adjusts discrete noise sampling settings for standard diffusion models.',
  'ModelSamplingFlux': 'Adjusts the noise sampling shift settings for Flux models.',
  'ModelSamplingLTXV': 'Adjusts the noise sampling shift settings for LTXV models.',
  'ModelSamplingSD3': 'Adjusts the noise sampling shift settings for Stable Diffusion 3 models.',
  'ModelSamplingStableCascade': 'Adjusts the noise sampling shift settings for Stable Cascade models.',
  'ModelSave': 'Saves a model to disk as a checkpoint file.',
  'MoonvalleyImg2VideoNode': 'Turns an image into a video using Moonvalley Marey API.',
  'MoonvalleyTxt2VideoNode': 'Creates a video from a text description using Moonvalley Marey API.',
  'MoonvalleyVideo2VideoNode': 'Transforms an existing video based on a text prompt using Moonvalley API.',
  'Morphology': 'Applies morphological operations like erode or dilate to reshape image features.',
  'NAGuidance': 'Applies normalized attention guidance to improve image generation quality.',
  'NormalizeImages': 'Adjusts image pixel values to a standard mean and deviation for training.',
  'NormalizeVideoLatentStart': 'Normalizes the starting frames of the AI\'s internal video data for consistency.',
  'OpenAIChatConfig': 'Sets advanced options for OpenAI ChatGPT text generation.',
  'OpenAIChatNode': 'Generates text responses using OpenAI ChatGPT from a prompt.',
  'OpenAIDalle2': 'Generates an image from a text prompt using OpenAI DALL-E 2 API.',
  'OpenAIDalle3': 'Generates an image from a text prompt using OpenAI DALL-E 3 API.',
  'OpenAIGPTImage1': 'Generates an image from a text prompt using OpenAI GPT Image 1.5.',
  'OpenAIInputFiles': 'Loads input files to include in an OpenAI ChatGPT conversation.',
  'OpenAIVideoSora2': 'Creates a video from a text prompt using OpenAI Sora API.',
  'OptimalStepsScheduler': 'Creates an optimized noise schedule tuned for specific model types.',
  'OutpaintImageNode': 'Extends an image beyond its borders with AI-invented surroundings, using Flux Fill (directional/zoom) or Bria Expand (target aspect ratio).',
  'Painter': 'Opens a drawing canvas to paint an image and mask by hand.',
  'PairConditioningCombine': 'Combines two pairs of positive and negative text guidance together.',
  'PairConditioningSetDefaultCombine': 'Sets a default text guidance pair and combines it with another.',
  'PairConditioningSetProperties': 'Adjusts the strength and timing properties of a text guidance pair.',
  'PairConditioningSetPropertiesAndCombine': 'Adjusts properties of a text guidance pair and combines it with another.',
  'PatchModelAddDownscale': 'Speeds up generation by temporarily reducing internal resolution during processing.',
  'PerpNeg': 'Applies perpendicular negative guidance to improve image quality (deprecated).',
  'PerpNegGuider': 'Creates a guider that uses perpendicular negative guidance for better results.',
  'PerturbedAttentionGuidance': 'Improves image details by perturbing the model\'s attention during generation.',
  'PersonSwapVideo': 'Replaces the person in a video with the person in a photo.',
  'PhotoMakerEncode': 'Encodes a face photo for use with PhotoMaker to create personalized images.',
  'PhotoMakerLoader': 'Loads a PhotoMaker model for generating personalized face images.',
  'PixverseImageToVideoNode': 'Turns an image into a video using PixVerse API.',
  'PixverseTemplateNode': 'Selects a video style template for PixVerse video generation.',
  'PixverseTextToVideoNode': 'Creates a video from a text description using PixVerse API.',
  'PixverseTransitionVideoNode': 'Creates a transition video between two images using PixVerse API.',
  'PolyexponentialScheduler': 'Creates a noise schedule using polyexponential curves for custom generation.',
  'PorterDuffImageComposite': 'Combines two images with transparency using Porter-Duff blending modes.',
  'Preview3D': 'Displays a 3D model or animation preview in the browser.',
  'PreviewAny': 'Displays any input value as text for quick inspection.',
  'PreviewAudio': 'Plays back an audio clip for listening in the browser.',
  'PreviewImage': 'Displays an image preview in the workflow editor.',
  'PrimitiveBoolean': 'Provides a true or false value to connect to other nodes.',
  'PrimitiveBoundingBox': 'Defines a rectangular area with position, width, and height values.',
  'PrimitiveFloat': 'Provides a decimal number value to connect to other nodes.',
  'PrimitiveInt': 'Provides a whole number value to connect to other nodes.',
  'PrimitiveString': 'Provides a single-line text value to connect to other nodes.',
  'PrimitiveStringMultiline': 'Provides a multi-line text value to connect to other nodes.',
  'QuadrupleCLIPLoader': 'Loads four text encoder models at once for advanced multi-encoder setups.',
  'QwenImageDiffsynthControlnet': 'Loads and applies a Qwen image diffusion control model for guided generation.',
  'RandomCropImages': 'Randomly crops images to a specified size for data augmentation.',
  'RandomNoise': 'Creates random noise from a seed for use in custom image generation.',
  'RebatchImages': 'Reorganizes images into batches of a specified size.',
  'RebatchLatents': 'Reorganizes the AI\'s internal image data into batches of a specified size.',
  'RecordAudio': 'Records audio from your microphone for use in the workflow.',
  'RecraftColorRGB': 'Defines a color using red, green, and blue values for Recraft API.',
  'RecraftControls': 'Sets control options for Recraft image generation.',
  'RecraftCreateStyleNode': 'Creates a custom art style from example images using Recraft API.',
  'RecraftCreativeUpscaleNode': 'Upscales an image with creative AI enhancement using Recraft API.',
  'RecraftCrispUpscaleNode': 'Upscales an image with sharp detail preservation using Recraft API.',
  'RecraftImageInpaintingNode': 'Fills in masked areas of an image based on a text prompt using Recraft.',
  'RecraftImageToImageNode': 'Transforms an image based on a text prompt using Recraft API.',
  'RecraftRemoveBackgroundNode': 'Removes the background from an image using Recraft API.',
  'RecraftReplaceBackgroundNode': 'Replaces the background of an image with a new one using Recraft API.',
  'RecraftStyleV3DigitalIllustration': 'Selects a digital illustration substyle for Recraft image generation.',
  'RecraftStyleV3InfiniteStyleLibrary': 'Loads a custom style from the Recraft infinite style library.',
  'RecraftStyleV3LogoRaster': 'Selects a raster logo substyle for Recraft image generation.',
  'RecraftStyleV3RealisticImage': 'Selects a realistic image substyle for Recraft image generation.',
  'RecraftTextToImageNode': 'Generates an image from a text description using Recraft API.',
  'RecraftTextToVectorNode': 'Generates a vector graphic from a text description using Recraft API.',
  'RecraftV4TextToImageNode': 'Generates an image from a text prompt using Recraft V4 API.',
  'RecraftV4TextToVectorNode': 'Generates a vector graphic from a text prompt using Recraft V4 API.',
  'RecraftVectorizeImageNode': 'Converts a raster image into a vector graphic using Recraft API.',
  'ReferenceLatent': 'Adds a reference image to guide the AI during image editing.',
  'ReferenceTimbreAudio': 'Provides a reference audio clip to guide the tone of audio generation.',
  'RegexExtract': 'Extracts matching text from a string using a regular expression pattern.',
  'RegexMatch': 'Checks whether a string matches a regular expression pattern and returns true or false.',
  'RegexReplace': 'Replaces parts of a string that match a regular expression pattern with new text.',
  'RenormCFG': 'Adjusts the AI model to renormalize generation guidance for more stable image results.',
  'RepeatImageBatch': 'Duplicates an image a specified number of times into a batch.',
  'RepeatLatentBatch': 'Duplicates the AI\'s internal image data a specified number of times into a batch.',
  'ReplaceText': 'Finds and replaces specific text within a collection of strings.',
  'ReplaceVideoLatentFrames': 'Swaps specific frames in the AI\'s internal video data at a chosen position.',
  'RescaleCFG': 'Adjusts the AI model\'s generation guidance strength to reduce overexposure artifacts.',
  'ResizeAndPadImage': 'Resizes an image to target dimensions and adds padding to preserve proportions.',
  'ResizeImageMaskNode': 'Resizes an image or mask to new dimensions using a chosen scaling method.',
  'ResizeImagesByLongerEdge': 'Resizes a batch of images so the longer edge matches a target size.',
  'ResizeImagesByShorterEdge': 'Resizes a batch of images so the shorter edge matches a target size.',
  'ResolutionBucket': 'Sorts training data into matching resolution groups for efficient batch processing.',
  'ResolutionSelector': 'Picks width and height values from a chosen aspect ratio and megapixel count.',
  'RestyleWithLoRANode': 'Restyles your image in a trained style LoRA while keeping its structure — captions it, restyles with Flux, then transfers the look with Nano Banana 2.',
  'ReveImageCreateNode': 'Generates an image from a text prompt using the Reve cloud API.',
  'ReveImageEditNode': 'Edits an existing image based on text instructions using the Reve cloud API.',
  'ReveImageRemixNode': 'Creates a new image inspired by reference images and a text prompt via Reve API.',
  'Rodin3D_Detail': 'Generates a detailed 3D model from images using the Rodin cloud API.',
  'Rodin3D_Gen2': 'Generates a 3D model from images using the Rodin Gen-2 cloud API.',
  'Rodin3D_Regular': 'Generates a standard 3D model from images using the Rodin cloud API.',
  'Rodin3D_Sketch': 'Generates a 3D model from sketch images using the Rodin cloud API.',
  'Rodin3D_Smooth': 'Generates a smooth 3D model from images using the Rodin cloud API.',
  'RunwayFirstLastFrameNode': 'Creates a video from first and last frame images using Runway cloud API.',
  'RunwayImageToVideoNodeGen3a': 'Converts an image into a video using Runway Gen3a Turbo cloud API.',
  'RunwayImageToVideoNodeGen4': 'Converts an image into a video using Runway Gen4 Turbo cloud API.',
  'RunwayTextToImageNode': 'Generates an image from a text prompt using the Runway cloud API.',
  'SDPoseDrawKeypoints': 'Draws body pose keypoints onto an image for visualization.',
  'SDPoseFaceBBoxes': 'Detects face regions from pose keypoints and outputs bounding boxes around them.',
  'SDPoseKeypointExtractor': 'Extracts body pose keypoints from an image for pose-guided generation.',
  'SDTurboScheduler': 'Creates a fast noise schedule optimized for turbo-speed image generation.',
  'SD_4XUpscale_Conditioning': 'Prepares text guidance for 4x upscaling an image with added detail.',
  'SV3D_Conditioning': 'Prepares text guidance for generating 3D multi-view images from a single photo.',
  'SVD_img2vid_Conditioning': 'Prepares text guidance for turning a single image into a video sequence.',
  'SamplerCustom': 'Generates images using customizable noise and sampling settings with full control.',
  'SamplerCustomAdvanced': 'Generates images with advanced custom noise, guider, and sampler configurations.',
  'SamplerDPMAdaptative': 'Creates an adaptive DPM sampling method that adjusts step size automatically.',
  'SamplerDPMPP_2M_SDE': 'Creates a DPM++ 2M SDE sampling method for image generation.',
  'SamplerDPMPP_2S_Ancestral': 'Creates a DPM++ 2S ancestral sampling method for image generation.',
  'SamplerDPMPP_3M_SDE': 'Creates a DPM++ 3M SDE sampling method for image generation.',
  'SamplerDPMPP_SDE': 'Creates a DPM++ SDE sampling method for image generation.',
  'SamplerER_SDE': 'Creates an ER-SDE sampling method for image generation.',
  'SamplerEulerAncestral': 'Creates an Euler ancestral sampling method for image generation.',
  'SamplerEulerAncestralCFGPP': 'Creates an improved Euler ancestral sampling method with enhanced guidance.',
  'SamplerEulerCFGpp': 'Creates an improved Euler sampling method with enhanced guidance for testing.',
  'SamplerLCMUpscale': 'Creates a sampling method that upscales images during the generation process.',
  'SamplerLMS': 'Creates a Linear Multi-Step sampling method for image generation.',
  'SamplerSASolver': 'Creates an SA-Solver sampling method for image generation.',
  'SamplerSEEDS2': 'Creates a SEEDS2 sampling method for image generation.',
  'SamplingPercentToSigma': 'Converts a sampling percentage value to its corresponding noise level number.',
  'SaveAnimatedPNG': 'Saves a sequence of images as an animated PNG file.',
  'SaveAnimatedWEBP': 'Saves a sequence of images as an animated WebP file.',
  'SaveAudio': 'Saves audio to a FLAC file on disk.',
  'SaveAudioMP3': 'Saves audio to an MP3 file on disk.',
  'SaveAudioOpus': 'Saves audio to an Opus file on disk.',
  'SaveGLB': 'Saves a 3D model to a file in various 3D formats.',
  'SaveImage': 'Saves an image to a file on disk.',
  'SaveImageDataSetToFolder': 'Saves a batch of training images to a specified folder on disk.',
  'SaveImageTextDataSetToFolder': 'Saves paired images and text descriptions to a folder for training datasets.',
  'SaveImageWebsocket': 'Sends generated images to a connected application through a websocket.',
  'SaveLatent': 'Saves the AI\'s internal image data to a file for later reuse.',
  'SaveLoRA': 'Saves trained style or concept weights to a file for later reuse.',
  'SaveSVGNode': 'Saves a vector graphic as an SVG file on disk.',
  'SaveTrainingDataset': 'Saves prepared training data to a folder for AI model fine-tuning.',
  'SaveVideo': 'Saves a video to a file on disk in a chosen format.',
  'SaveWEBM': 'Saves a sequence of images as a WebM video file.',
  'ScaleROPE': 'Adjusts the AI model\'s position encoding to handle different image resolutions.',
  'SeedreamLayerizeNode': 'Splits a finished image into 2-17 independent transparent-PNG raster layers (background plus separate elements), editable as Compositor image layers, using Seedream 5 Pro Layerize.',
  'SelfAttentionGuidance': 'Adjusts the AI model to improve image sharpness and reduce artifacts.',
  'SetClipHooks': 'Configures advanced hooks on the text encoder for custom behavior.',
  'SetFirstSigma': 'Sets the starting noise level for a custom noise schedule.',
  'SetHookKeyframes': 'Assigns timing keyframes to control when hooks activate during generation.',
  'SetLatentNoiseMask': 'Applies a mask to the AI\'s internal image data to define inpainting regions.',
  'SetUnionControlNetType': 'Sets the control type for a union control net to guide image generation.',
  'ShaderEffect': 'Real-time shader effects — distortion, halftone, dither, and more. Live animated preview; renders locally on your GPU at no credit cost.',
  'ShuffleDataset': 'Randomly reorders a batch of training images using a seed value.',
  'ShuffleImageTextDataset': 'Randomly reorders paired images and text together using a seed value.',
  'SkipLayerGuidanceDiT': 'Skips specific model layers during generation to change the output style.',
  'SkipLayerGuidanceDiTSimple': 'Skips specific model layers during generation for simplified style control.',
  'SkipLayerGuidanceSD3': 'Skips specific layers in SD3 models to adjust generation style and detail.',
  'SolidMask': 'Creates a solid-colored mask with a specified size and brightness value.',
  'SplitAudioChannels': 'Splits stereo audio into separate left and right channel outputs.',
  'SplitImageToTileList': 'Divides an image into a grid of smaller tile images.',
  'SplitImageWithAlpha': 'Separates an image into its color layer and transparency mask.',
  'SplitPhotoLayersNode': 'Splits a photo into a transparent subject cutout and a clean background plate (subject removed and filled), using a background remover plus LaMa or Flux Fill.',
  'SplitSigmas': 'Splits a noise schedule into two parts at a specified step number.',
  'SplitSigmasDenoise': 'Splits a noise schedule into two parts based on a denoise strength value.',
  'StabilityAudioInpaint': 'Fills in missing or selected sections of audio using Stability AI cloud API.',
  'StabilityAudioToAudio': 'Transforms existing audio based on a text prompt using Stability AI cloud API.',
  'StabilityStableImageSD_3_5Node': 'Generates an image from a text prompt using Stability AI SD 3.5 cloud API.',
  'StabilityStableImageUltraNode': 'Generates a high-quality image from a text prompt using Stability AI Ultra API.',
  'StabilityTextToAudio': 'Generates audio from a text description using Stability AI cloud API.',
  'StabilityUpscaleConservativeNode': 'Enlarges an image with minimal changes using Stability AI cloud API.',
  'StabilityUpscaleCreativeNode': 'Enlarges an image with creative detail enhancement using Stability AI cloud API.',
  'StabilityUpscaleFastNode': 'Quickly enlarges an image using Stability AI cloud API.',
  'StableCascade_EmptyLatentImage': 'Creates empty internal image data sized for the Stable Cascade generation pipeline.',
  'StableCascade_StageB_Conditioning': 'Prepares Stage B text guidance for Stable Cascade image generation pipeline.',
  'StableCascade_StageC_VAEEncode': 'Converts an image into Stable Cascade internal data format for processing.',
  'StableCascade_SuperResolutionControlnet': 'Upscales images using Stable Cascade super-resolution control for added detail.',
  'StableZero123_Conditioning': 'Prepares text guidance for generating new 3D viewpoints from a single image.',
  'StableZero123_Conditioning_Batched': 'Prepares batched text guidance for generating multiple 3D viewpoints from one image.',
  'StringCompare': 'Compares two text strings and returns whether they match.',
  'StringConcatenate': 'Joins two text strings together with an optional separator between them.',
  'StringContains': 'Checks whether a text string contains a specific substring.',
  'StringLength': 'Counts the number of characters in a text string.',
  'StringReplace': 'Finds and replaces specific text within a string.',
  'StringSubstring': 'Extracts a portion of text between specified start and end positions.',
  'StringTrim': 'Removes extra whitespace from the beginning, end, or both sides of text.',
  'StripWhitespace': 'Removes all leading and trailing whitespace from text entries.',
  'StyleModelApply': 'Applies a loaded style model to text guidance for style-controlled generation.',
  'StyleModelLoader': 'Loads a style model file for applying artistic styles to generated images.',
  'T5TokenizerOptions': 'Configures padding and length settings for the T5 text encoder.',
  'TCFG': 'Applies tangential damping to the AI model\'s guidance for smoother image results.',
  'TemporalScoreRescaling': 'Adjusts video model scores over time to improve temporal consistency in videos.',
  'Tencent3DPartNode': 'Generates 3D model parts using the Hunyuan3D cloud API.',
  'Tencent3DTextureEditNode': 'Edits 3D model textures with a text prompt using Hunyuan3D cloud API.',
  'TencentImageToModelNode': 'Converts images into a 3D model using the Hunyuan3D cloud API.',
  'TencentModelTo3DUVNode': 'Adds UV texture mapping to a 3D model using Hunyuan3D cloud API.',
  'TencentSmartTopologyNode': 'Optimizes 3D model mesh topology using Hunyuan3D cloud API.',
  'TencentTextToModelNode': 'Generates a 3D model from a text description using Hunyuan3D cloud API.',
  'TextEncodeAceStepAudio': 'Converts music tags and lyrics into text guidance for audio generation.',
  'TextEncodeAceStepAudio1.5': 'Converts music tags and lyrics into text guidance for audio generation v1.5.',
  'TextEncodeHunyuanVideo_ImageToVideo': 'Converts a text prompt and image into text guidance for Hunyuan video generation.',
  'TextEncodeQwenImageEdit': 'Converts a text prompt into text guidance for Qwen-based image editing.',
  'TextEncodeQwenImageEditPlus': 'Converts a text prompt into enhanced text guidance for Qwen-based image editing.',
  'TextEncodeZImageOmni': 'Converts a text prompt into text guidance for ZImage Omni generation.',
  'TextGenerate': 'Generates new text from a prompt using a language model.',
  'TextGenerateLTX2Prompt': 'Generates an enhanced prompt for LTX2 video generation from a short description.',
  'TextToLowercase': 'Converts all text to lowercase letters.',
  'TextToUppercase': 'Converts all text to uppercase letters.',
  'ThresholdMask': 'Converts a mask to pure black and white based on a brightness cutoff value.',
  'TomePatchModel': 'Speeds up the AI model by merging similar internal tokens during generation.',
  'TopazImageEnhance': 'Enhances and upscales an image using the Topaz cloud API.',
  'TopazVideoEnhance': 'Enhances and upscales a video using the Topaz cloud API.',
  'TorchCompileModel': 'Compiles the AI model for faster execution using a chosen backend.',
  'TrainLoraNode': 'Trains custom style or concept weights from provided images and text guidance.',
  'TrimAudioDuration': 'Cuts audio to a specific start time and duration.',
  'TrimVideoLatent': 'Removes frames from the end of the AI\'s internal video data.',
  'TripleCLIPLoader': 'Loads three text encoder models at once for advanced multi-encoder workflows.',
  'TripoConversionNode': 'Converts a Tripo 3D model to a downloadable file format via cloud API.',
  'TripoImageToModelNode': 'Creates a 3D model from an image using the Tripo cloud API.',
  'TripoMultiviewToModelNode': 'Creates a 3D model from multiple view images using the Tripo cloud API.',
  'TripoRefineNode': 'Improves the quality of a draft 3D model using the Tripo cloud API.',
  'TripoRetargetNode': 'Applies animation retargeting to a rigged 3D model via Tripo cloud API.',
  'TripoRigNode': 'Adds a skeleton rig to a 3D model for animation via Tripo cloud API.',
  'TripoTextToModelNode': 'Creates a 3D model from a text description using the Tripo cloud API.',
  'TripoTextureNode': 'Adds textures to a 3D model using the Tripo cloud API.',
  'TruncateText': 'Shortens text to a maximum number of characters.',
  'UNETLoader': 'Loads a diffusion model file for image generation.',
  'UNetCrossAttentionMultiply': 'Adjusts cross-attention weights in the AI model to change prompt responsiveness.',
  'UNetSelfAttentionMultiply': 'Adjusts self-attention weights in the AI model to change detail coherence.',
  'UNetTemporalAttentionMultiply': 'Adjusts temporal attention weights in the AI model for video consistency control.',
  'USOStyleReference': 'Applies a visual style from a reference image to guide Flux model generation.',
  'UpscaleModelLoader': 'Loads an upscaling model file for enlarging images with AI enhancement.',
  'VAEDecode': 'Converts the AI\'s internal image data back into a viewable image.',
  'VAEDecodeAudio': 'Converts the AI\'s internal audio data back into playable audio.',
  'VAEDecodeAudioTiled': 'Converts the AI\'s internal audio data into playable audio using tiled processing.',
  'VAEDecodeHunyuan3D': 'Converts the AI\'s internal 3D data into a viewable voxel model.',
  'VAEDecodeTiled': 'Converts the AI\'s internal image data into a viewable image using tiled processing.',
  'VAEEncode': 'Converts a viewable image into the AI\'s internal image data for processing.',
  'VAEEncodeAudio': 'Converts playable audio into the AI\'s internal audio data for processing.',
  'VAEEncodeForInpaint': 'Converts an image and mask into the AI\'s internal data for inpainting.',
  'VAEEncodeTiled': 'Converts a viewable image into the AI\'s internal data using tiled processing.',
  'VAELoader': 'Loads an image decoder/encoder model file for converting between images and internal data.',
  'VAESave': 'Saves an image decoder/encoder model to a file for later reuse.',
  'VPScheduler': 'Creates a variance-preserving noise schedule for custom image generation.',
  'Veo3FirstLastFrameNode': 'Creates a video from first and last frames using Google Veo 3 cloud API.',
  'Veo3VideoGenerationNode': 'Generates a video from a text prompt using Google Veo 3 cloud API.',
  'VeoVideoGenerationNode': 'Generates a video from a text prompt using Google Veo 2 cloud API.',
  'Video Slice': 'Extracts a portion of a video between a start time and duration.',
  'VideoLinearCFGGuidance': 'Applies linearly decreasing guidance strength across video frames for smoother motion.',
  'VideoTriangleCFGGuidance': 'Applies triangle-shaped guidance strength across video frames for smoother motion.',
  'Vidu2ImageToVideoNode': 'Converts an image into a video using Vidu2 cloud API.',
  'Vidu2ReferenceVideoNode': 'Generates a video from reference subjects and a prompt using Vidu2 cloud API.',
  'Vidu2StartEndToVideoNode': 'Creates a video from start and end frame images using Vidu2 cloud API.',
  'Vidu2TextToVideoNode': 'Generates a video from a text prompt using Vidu2 cloud API.',
  'Vidu3ImageToVideoNode': 'Converts an image into a video using Vidu Q3 cloud API.',
  'Vidu3StartEndToVideoNode': 'Creates a video from start and end frame images using Vidu Q3 cloud API.',
  'Vidu3TextToVideoNode': 'Generates a video from a text prompt using Vidu Q3 cloud API.',
  'ViduExtendVideoNode': 'Extends an existing video with new frames using Vidu cloud API.',
  'ViduImageToVideoNode': 'Converts an image into a video using the Vidu cloud API.',
  'ViduMultiFrameVideoNode': 'Generates a video from multiple key frame images using Vidu cloud API.',
  'ViduReferenceVideoNode': 'Generates a video from reference images and a prompt using Vidu cloud API.',
  'ViduStartEndToVideoNode': 'Creates a video from start and end frame images using Vidu cloud API.',
  'ViduTextToVideoNode': 'Generates a video from a text prompt using the Vidu cloud API.',
  'VoxelToMesh': 'Converts a voxel 3D model into a polygon mesh using a chosen algorithm.',
  'VoxelToMeshBasic': 'Converts a voxel 3D model into a basic polygon mesh.',
  'Wan22FunControlToVideo': 'Prepares controlled video text guidance for the Wan 2.2 Fun video model.',
  'Wan22ImageToVideoLatent': 'Creates empty internal video data from image dimensions for Wan 2.2 processing.',
  'WanAnimateToVideo': 'Prepares animation-guided text guidance for Wan video generation.',
  'WanCameraEmbedding': 'Creates camera movement data to control virtual camera motion in Wan videos.',
  'WanCameraImageToVideo': 'Prepares camera-controlled text guidance for Wan image-to-video generation.',
  'WanContextWindowsManual': 'Configures manual context window settings for processing long Wan videos.',
  'WanFirstLastFrameToVideo': 'Prepares text guidance for Wan video generation from first and last frames.',
  'WanFunControlToVideo': 'Prepares controlled video text guidance for the Wan Fun video model.',
  'WanFunInpaintToVideo': 'Prepares inpainting text guidance for the Wan Fun video model.',
  'WanHuMoImageToVideo': 'Prepares human motion text guidance for Wan image-to-video generation.',
  'WanImageToImageApi': 'Transforms an image based on a text prompt using Wan cloud API.',
  'WanImageToVideo': 'Prepares text guidance for turning a single image into a Wan video.',
  'WanImageToVideoApi': 'Converts an image into a video using the Wan cloud API.',
  'WanInfiniteTalkToVideo': 'Prepares talking-head text guidance for generating Wan conversation videos.',
  'WanMoveConcatTrack': 'Combines multiple motion tracking paths into one for Wan video generation.',
  'WanMoveTrackToVideo': 'Prepares motion-tracked text guidance for Wan video object movement control.',
  'WanMoveTracksFromCoords': 'Creates motion tracking paths from coordinate points for Wan video generation.',
  'WanMoveVisualizeTracks': 'Draws motion tracking paths onto images for preview and debugging.',
  'WanPhantomSubjectToVideo': 'Prepares subject-driven text guidance for Wan video generation with custom subjects.',
  'WanReferenceVideoApi': 'Generates a video from reference content and a prompt using Wan cloud API.',
  'WanSCAILToVideo': 'Prepares SCAIL-guided text guidance for enhanced Wan video generation.',
  'WanSoundImageToVideo': 'Prepares sound-driven text guidance for Wan image-to-video generation with audio.',
  'WanSoundImageToVideoExtend': 'Extends a sound-driven Wan video with additional audio-guided frames.',
  'WanTextToImageApi': 'Generates an image from a text prompt using the Wan cloud API.',
  'WanTextToVideoApi': 'Generates a video from a text prompt using the Wan cloud API.',
  'WanTrackToVideo': 'Prepares object-tracking text guidance for Wan video generation.',
  'WanVaceToVideo': 'Prepares versatile all-in-one text guidance for Wan video creation.',
  'WavespeedFlashVSRNode': 'Upscales video resolution using the WaveSpeed cloud API.',
  'WavespeedImageUpscaleNode': 'Upscales image resolution using the WaveSpeed cloud API.',
  'WebcamCapture': 'Captures a live image frame from your webcam at a specified resolution.',
  'ZImageFunControlnet': 'Loads and applies ZImage Fun control net settings for guided image generation.',
  'unCLIPCheckpointLoader': 'Loads an unCLIP model checkpoint for image-guided generation workflows.',
  'unCLIPConditioning': 'Adds image-based guidance to text guidance for image-influenced generation.',
  'wanBlockSwap': 'Optimizes Wan model memory usage by swapping blocks between GPU and CPU.',
}
