/**
 * The shape library — a typed, pure catalog over the committed manifest
 * (app/data/shape-library.manifest.json, generated by scripts/build-shape-library.mjs
 * from Assets/Shapes/*.svg). Every consumer — the Space Type separator, the
 * Compositor shape layer, Shape Studio, 3D Studio, the agent — reads shapes
 * through here. No DOM, no network: safe in the headless bake and the embed.
 */
import manifest from '~/data/shape-library.manifest.json'
import type { LibraryShape, ShapeManifest } from '~~/shared/shape-library'

export type { LibraryShape } from '~~/shared/shape-library'

export const SHAPE_MANIFEST = manifest as unknown as ShapeManifest
export const SHAPES: readonly LibraryShape[] = SHAPE_MANIFEST.shapes

/** The "no shape" value a `shape` control stores. */
export const SHAPE_NONE = 'none'

const byId = new Map<string, LibraryShape>(SHAPES.map(s => [s.id, s]))

export function shapeById(id: string): LibraryShape | undefined {
  return byId.get(id)
}

export function isShapeId(v: unknown): v is string {
  return typeof v === 'string' && byId.has(v)
}

export type ShapeFamily = 'geometric' | 'suns' | 'botanical' | 'patterns' | 'symbols' | 'diagram'

/** Rail order. Labels are plain words a casual user recognises. */
export const SHAPE_FAMILIES: { id: ShapeFamily; label: string }[] = [
  { id: 'geometric', label: 'Geometric' },
  { id: 'suns', label: 'Suns & sparkles' },
  { id: 'botanical', label: 'Botanical' },
  { id: 'patterns', label: 'Patterns' },
  { id: 'symbols', label: 'Symbols' },
  { id: 'diagram', label: 'Diagram' },
]

/**
 * First matching rule wins. Patterns go first so `square-strokes-*` and
 * `*-pattern-*` land there before the geometric prefixes claim them. A shape
 * that matches nothing is reported by `familyRuleFor` as null (the manifest
 * test fails on it) and shown under Symbols by `familyOf`.
 */
const FAMILY_RULES: [ShapeFamily, RegExp][] = [
  ['patterns', /pattern|strokes|repeat|-tile$/],
  ['suns', /^(sun-|sparkle|explosion$|spin$|splash$)/],
  ['botanical', /^(leaf|flower|floral|cloud$|circle-cloud$|heart$|swirl$|spiral$|wave$)/],
  ['diagram', /^(diagram-|pie-chart$|circle-network$|stairs$)/],
  ['symbols', /^(x|z|plus|badge|clover-x)$/],
  ['geometric', /^(circle|cone$|cylinder$|decagon$|dodecagon$|ellipse|half-circle|hendecagon$|heptagon$|hexagon$|nanogon$|octagon$|pentagon$|polygon$|parallelogram|rhombus|square|trapezoid$|triangle|kite$|intersect|corner-radius$|beak|gate$|umbrella-top$)/],
]

export function familyRuleFor(id: string): ShapeFamily | null {
  for (const [fam, re] of FAMILY_RULES) if (re.test(id)) return fam
  return null
}

export function familyOf(id: string): ShapeFamily {
  return familyRuleFor(id) ?? 'symbols'
}

/** Case-insensitive substring over id and name. '' ⇒ everything, manifest order. */
export function searchShapes(query: string): LibraryShape[] {
  const q = query.trim().toLowerCase()
  if (!q) return [...SHAPES]
  const qDashed = q.replace(/\s+/g, '-')
  return SHAPES.filter(s => s.id.toLowerCase().includes(qDashed) || s.name.toLowerCase().includes(q))
}

/** The option list a `shape` control exposes to the agent: 'none' first when allowed, then every id. */
export function shapeOptions(allowNone: boolean): string[] {
  return [...(allowNone ? [SHAPE_NONE] : []), ...SHAPES.map(s => s.id)]
}
