/** One entry of app/data/shape-library.manifest.json (generated by scripts/build-shape-library.mjs). */
export interface LibraryShape {
  /** Slug of the SVG filename, e.g. 'sun-rays'. Stable id for params and the agent. */
  id: string
  /** Display name, e.g. 'Sun rays'. */
  name: string
  /** Absolute path data (only M L C Z) in the 96×96 source box. */
  d: string
  fillRule: 'nonzero' | 'evenodd'
  /** Ink bounding box [x, y, w, h] in source units. Consumers fit by this, not by the 96 box. */
  box: [number, number, number, number]
  /** The SVG's fill, kept as a hint only. Never used to paint. */
  sourceColor: string
}

export interface ShapeManifest {
  generatedAt: string
  shapesRoot: string
  shapes: LibraryShape[]
}
